In [54]:
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf

In [194]:
listings = pd.read_csv('may_master_list2.csv')

In [83]:
calendar = pd.read_csv('may_master_cal_edited.csv')

In [84]:
calendar.head()

   Unnamed: 0  listing_id        date available   price  year
0           0       74758  2020-05-06         t  $35.00  2020
1           1       74758  2020-05-07         t  $35.00  2020
2           2       74758  2020-05-08         t  $35.00  2020
3           3       74758  2020-05-09         t  $35.00  2020
4           4       74758  2020-05-10         t  $35.00  2020

In [168]:
listings.head()

,Unnamed: 0,id,scrape_id,last_scraped,description,host_id,host_total_listings_count,street,neighbourhood,city,...,has_availability,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_location,review_scores_value,requires_license,license,calculated_host_listings_count,year
0,0,958,20200506054328,2020-05-06,New update: the house next door is under const...,1169,1.0,"San Francisco, CA, United States",Lower Haight,San Francisco,...,t,241,97.0,10.0,10.0,10.0,t,STR-0001256,1,2020
1,1,5858,20200506054328,2020-05-06,We live in a large Victorian house on a quiet ...,8904,2.0,"San Francisco, CA, United States",Bernal Heights,San Francisco,...,t,111,98.0,10.0,10.0,9.0,t,NaN,1,2020
2,2,7918,20200506054328,2020-05-06,Nice and good public transportation. 7 minute...,21994,10.0,"San Francisco, CA, United States",Cole Valley,San Francisco,...,t,19,84.0,7.0,9.0,8.0,t,NaN,9,2020
3,3,8142,20200506054328,2020-05-06,Nice and good public transportation. 7 minute...,21994,10.0,"San Francisco, CA, United States",Cole Valley,San Francisco,...,t,8,93.0,9.0,9.0,9.0,t,NaN,9,2020
4,4,8339,20200506054328,2020-05-06,Pls email before booking. Interior featured i...,24215,2.0,"San Francisco, CA, United States",Western Addition/NOPA,San Francisco,...,t,28,97.0,10.0,10.0,10.0,t,STR-0000264,2,2020

In [169]:
listings.columns

Index(['Unnamed: 0', 'id', 'scrape_id', 'last_scraped', 'description',
       'host_id', 'host_total_listings_count', 'street', 'neighbourhood',
       'city', 'state', 'zipcode', 'country_code', 'country', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bedrooms', 'beds', 'square_feet', 'price', 'has_availability',
       'number_of_reviews', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_location', 'review_scores_value', 'requires_license',
       'license', 'calculated_host_listings_count', 'year'],
      dtype='object')

In [195]:
listings['price'] = listings['price'].str.replace('$', '')
listings['price'] = listings['price'].str.replace(',', '')

In [59]:
from sklearn.model_selection import train_test_split

In [196]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42486 entries, 0 to 42485
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      42486 non-null  int64
 1   id                              42486 non-null  int64
 2   scrape_id                       42486 non-null  int64
 3   last_scraped                    42486 non-null  object
 4   description                     42387 non-null  object
 5   host_id                         42486 non-null  int64
 6   host_total_listings_count       37006 non-null  float64
 7   street                          42486 non-null  object
 8   neighbourhood                   40491 non-null  object
 9   city                            42475 non-null  object
 10  state                           42468 non-null  object
 11  zipcode                         42041 non-null  object
 12  country_code                    37061 non-null  object
 13  country                         42486 non-null  object
 14  latitude                        42486 non-null  float64
 15  longitude                       42486 non-null  float64
 16  property_type                   42471 non-null  object
 17  room_type                       42486 non-null  object
 18  accommodates                    42486 non-null  int64
 19  bathrooms                       42301 non-null  float64
 20  bedrooms                        42456 non-null  float64
 21  beds                            42401 non-null  float64
 22  square_feet                     993 non-null    float64
 23  price                           42486 non-null  object
 24  has_availability                20205 non-null  object
 25  number_of_reviews               42486 non-null  int64
 26  review_scores_rating            33180 non-null  float64
 27  review_scores_accuracy          33126 non-null  float64
 28  review_scores_location          33113 non-null  float64
 29  review_scores_value             33105 non-null  float64
 30  requires_license                42486 non-null  object
 31  license                         16076 non-null  object
 32  calculated_host_listings_count  42486 non-null  int64
 33  year                            42486 non-null  int64
dtypes: float64(11), int64(8), object(15)
memory usage: 11.0+ MB

In [197]:
listings['price'] = listings.price.astype(float)

In [198]:
zipcode = listings['zipcode']

In [204]:
zipcode.value_counts()

94110     1859
94117     1282
94114     1243
94109     1142
94102     1001
          ...
             2
941290       1
94130        1
94129        1
941580       1
Name: zipcode, Length: 72, dtype: int64

In [203]:
listings['zipcode'] = listings['zipcode'].str.replace('CA', '')

In [ ]:
listings['zipcode'] = listings['zipcode'].str.replace('.', '')

In [186]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42486 entries, 0 to 42485
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      42486 non-null  int64
 1   id                              42486 non-null  int64
 2   scrape_id                       42486 non-null  int64
 3   last_scraped                    42486 non-null  object
 4   description                     42387 non-null  object
 5   host_id                         42486 non-null  int64
 6   host_total_listings_count       37006 non-null  float64
 7   street                          42486 non-null  object
 8   neighbourhood                   40491 non-null  object
 9   city                            42475 non-null  object
 10  state                           42468 non-null  object
 11  zipcode                         42486 non-null  int64
 12  country_code                    37061 non-null  object
 13  country                         42486 non-null  object
 14  latitude                        42486 non-null  float64
 15  longitude                       42486 non-null  float64
 16  property_type                   42471 non-null  object
 17  room_type                       42486 non-null  object
 18  accommodates                    42486 non-null  int64
 19  bathrooms                       42301 non-null  float64
 20  bedrooms                        42456 non-null  float64
 21  beds                            42401 non-null  float64
 22  square_feet                     993 non-null    float64
 23  price                           42486 non-null  float64
 24  has_availability                20205 non-null  object
 25  number_of_reviews               42486 non-null  int64
 26  review_scores_rating            33180 non-null  float64
 27  review_scores_accuracy          33126 non-null  float64
 28  review_scores_location          33113 non-null  float64
 29  review_scores_value             33105 non-null  float64
 30  requires_license                42486 non-null  object
 31  license                         16076 non-null  object
 32  calculated_host_listings_count  42486 non-null  int64
 33  year                            42486 non-null  int64
dtypes: float64(12), int64(9), object(13)
memory usage: 11.0+ MB

In [193]:
listings.zipcode.value_counts()

150.0     1596
200.0     1332
100.0     1280
250.0     1252
125.0     1003
          ...
947.0        1
1895.0       1
1900.0       1
1675.0       1
24.0         1
Name: zipcode, Length: 700, dtype: int64

In [170]:
listings.dropna(inplace=True)

In [61]:
listings.year.astype(float)

0        2020.0
1        2020.0
2        2020.0
3        2020.0
4        2020.0
          ...
42481    2015.0
42482    2015.0
42483    2015.0
42484    2015.0
42485    2015.0
Name: year, Length: 42486, dtype: float64

In [ ]:
li

In [181]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42486 entries, 0 to 42485
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      42486 non-null  int64
 1   id                              42486 non-null  int64
 2   scrape_id                       42486 non-null  int64
 3   last_scraped                    42486 non-null  object
 4   description                     42387 non-null  object
 5   host_id                         42486 non-null  int64
 6   host_total_listings_count       37006 non-null  float64
 7   street                          42486 non-null  object
 8   neighbourhood                   40491 non-null  object
 9   city                            42475 non-null  object
 10  state                           42468 non-null  object
 11  zipcode                         42041 non-null  object
 12  country_code                    37061 non-null  object
 13  country                         42486 non-null  object
 14  latitude                        42486 non-null  float64
 15  longitude                       42486 non-null  float64
 16  property_type                   42471 non-null  object
 17  room_type                       42486 non-null  object
 18  accommodates                    42486 non-null  int64
 19  bathrooms                       42301 non-null  float64
 20  bedrooms                        42456 non-null  float64
 21  beds                            42401 non-null  float64
 22  square_feet                     993 non-null    float64
 23  price                           42486 non-null  float64
 24  has_availability                20205 non-null  object
 25  number_of_reviews               42486 non-null  int64
 26  review_scores_rating            33180 non-null  float64
 27  review_scores_accuracy          33126 non-null  float64
 28  review_scores_location          33113 non-null  float64
 29  review_scores_value             33105 non-null  float64
 30  requires_license                42486 non-null  object
 31  license                         16076 non-null  object
 32  calculated_host_listings_count  42486 non-null  int64
 33  year                            42486 non-null  int64
dtypes: float64(12), int64(8), object(14)
memory usage: 11.0+ MB

In [92]:
newdf = calendar.groupby(['year', 'available'])

In [95]:
calendar.groupby('year')

In [99]:
cal = calendar[['year', 'available']]

In [112]:
cal_total = cal.groupby('year')['available'].count()

In [119]:
cal_total['year', 'available'] = cal.groupby('year')['available'].count().reset_index()

KeyError: "None of [Index(['year', 'available'], dtype='object', name='year')] are in the [index]"

In [120]:
df1 = pd.DataFrame(data=cal, columns=['year'])
df2 = pd.DataFrame(data=cal_total, columns=['available'])
df = pd.merge(df1, df2, left_index=True, right_index=True)

In [121]:
df

      year  available
2015  2020    1979395
2016  2020    2951390
2017  2020    3201780
2018  2020    1742145
2019  2020    2683845
2020  2020    2948470

In [108]:
cal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15507025 entries, 0 to 15507024
Data columns (total 2 columns):
 #   Column     Dtype
---  ------     -----
 0   year       int64
 1   available  object
dtypes: int64(1), object(1)
memory usage: 236.6+ MB

In [165]:
listings.dropna(axis=1, thresh=n)

AttributeError: 'NoneType' object has no attribute 'dropna'

In [205]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42486 entries, 0 to 42485
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      42486 non-null  int64
 1   id                              42486 non-null  int64
 2   scrape_id                       42486 non-null  int64
 3   last_scraped                    42486 non-null  object
 4   description                     42387 non-null  object
 5   host_id                         42486 non-null  int64
 6   host_total_listings_count       37006 non-null  float64
 7   street                          42486 non-null  object
 8   neighbourhood                   40491 non-null  object
 9   city                            42475 non-null  object
 10  state                           42468 non-null  object
 11  zipcode                         16133 non-null  object
 12  country_code                    37061 non-null  object
 13  country                         42486 non-null  object
 14  latitude                        42486 non-null  float64
 15  longitude                       42486 non-null  float64
 16  property_type                   42471 non-null  object
 17  room_type                       42486 non-null  object
 18  accommodates                    42486 non-null  int64
 19  bathrooms                       42301 non-null  float64
 20  bedrooms                        42456 non-null  float64
 21  beds                            42401 non-null  float64
 22  square_feet                     993 non-null    float64
 23  price                           42486 non-null  float64
 24  has_availability                20205 non-null  object
 25  number_of_reviews               42486 non-null  int64
 26  review_scores_rating            33180 non-null  float64
 27  review_scores_accuracy          33126 non-null  float64
 28  review_scores_location          33113 non-null  float64
 29  review_scores_value             33105 non-null  float64
 30  requires_license                42486 non-null  object
 31  license                         16076 non-null  object
 32  calculated_host_listings_count  42486 non-null  int64
 33  year                            42486 non-null  int64
dtypes: float64(12), int64(8), object(14)
memory usage: 11.0+ MB

In [277]:
listings.bedrooms.value_counts()

1.0     9694
2.0     2848
0.0     1729
3.0     1365
4.0      394
5.0       64
6.0       24
7.0        5
14.0       2
9.0        1
8.0        1
Name: bedrooms, dtype: int64

In [285]:
listings.beds.value_counts()

1.0     8823
2.0     4013
3.0     1568
4.0      838
0.0      306
5.0      305
6.0      111
7.0       60
8.0       38
9.0        7
10.0       5
14.0       4
12.0       2
13.0       1
16.0       1
Name: beds, dtype: int64

In [293]:
listings.accommodates.value_counts()

2     7322
4     3177
1     1571
3     1297
6     1262
5      696
8      363
7      199
10      97
9       49
12      45
11      19
16      15
14      11
15      10
Name: accommodates, dtype: int64

In [324]:
listings.room_type.value_counts()

Entire home/apt    9607
Private room       5899
Shared room         465
Hotel room          111
Name: room_type, dtype: int64

In [325]:
listings.dropna(subset=['room_type'], inplace=True)

In [326]:
listings.dropna(subset=['beds'], inplace=True)

In [337]:
listings.dropna(subset=['neighbourhood'], inplace=True)

In [338]:
dummies = pd.get_dummies(df['neighbourhood'])

KeyError: 'neighbourhood'

In [339]:
y = listings['price']

In [340]:
X = listings[['year','neighbourhood','beds', 'room_type']]

In [341]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [342]:
listings_train = pd.concat([X_train, y_train], axis = 1)

In [343]:
listings_test = pd.concat([X_test,y_test], axis = 1)

In [332]:
listings_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3217 entries, 6149 to 8358
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           3217 non-null   int64
 1   neighbourhood  3217 non-null   object
 2   beds           3217 non-null   float64
 3   room_type      3217 non-null   object
 4   price          3217 non-null   float64
dtypes: float64(2), int64(1), object(2)
memory usage: 150.8+ KB

In [344]:
fitted_model = smf.ols(formula='price ~ year + beds + C(neighbourhood) + C(room_type)', data=listings, missing='drop').fit()

In [345]:
fitted_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.093
Model:                            OLS   Adj. R-squared:                  0.090
Method:                 Least Squares   F-statistic:                     27.82
Date:                Wed, 23 Sep 2020   Prob (F-statistic):          2.52e-288
Time:                        09:29:11   Log-Likelihood:            -1.1956e+05
No. Observations:               16081   AIC:                         2.392e+05
Df Residuals:                   16021   BIC:                         2.397e+05
Df Model:                          59
Covariance Type:            nonrobust
=============================================================================================================
                                                coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------
Intercept                                 -2.164e+04    1.1e+04     -1.961      0.050   -4.33e+04      -8.391
C(neighbourhood)[T.Balboa Terrace]          -59.3369     56.078     -1.058      0.290    -169.255      50.582
C(neighbourhood)[T.Bayview]                 -74.2884     43.458     -1.709      0.087    -159.471      10.894
C(neighbourhood)[T.Bernal Heights]          -46.6417     41.482     -1.124      0.261    -127.950      34.667
C(neighbourhood)[T.Chinatown]                18.3418     51.688      0.355      0.723     -82.972     119.656
C(neighbourhood)[T.Civic Center]            246.4562     69.434      3.550      0.000     110.358     382.554
C(neighbourhood)[T.Cole Valley]             -17.1233     47.388     -0.361      0.718    -110.010      75.763
C(neighbourhood)[T.Cow Hollow]               76.6650     52.921      1.449      0.147     -27.067     180.397
C(neighbourhood)[T.Crocker Amazon]          -95.6415     50.156     -1.907      0.057    -193.953       2.670
C(neighbourhood)[T.Daly City]              -124.8210    116.481     -1.072      0.284    -353.137     103.495
C(neighbourhood)[T.Diamond Heights]         -27.0435     79.539     -0.340      0.734    -182.949     128.862
C(neighbourhood)[T.Dogpatch]                 72.9289     63.179      1.154      0.248     -50.909     196.767
C(neighbourhood)[T.Downtown]                 60.1668     41.822      1.439      0.150     -21.808     142.142
C(neighbourhood)[T.Duboce Triangle]          39.7222     46.217      0.859      0.390     -50.869     130.313
C(neighbourhood)[T.Excelsior]               -97.4434     46.457     -2.098      0.036    -188.504      -6.383
C(neighbourhood)[T.Financial District]       13.8987     51.510      0.270      0.787     -87.067     114.864
C(neighbourhood)[T.Fisherman's Wharf]       225.1141     51.846      4.342      0.000     123.491     326.737
C(neighbourhood)[T.Forest Hill]             -24.9084     85.600     -0.291      0.771    -192.694     142.877
C(neighbourhood)[T.Glen Park]               -27.2460     51.790     -0.526      0.599    -128.760      74.268
C(neighbourhood)[T.Haight-Ashbury]          -21.6440     43.702     -0.495      0.620    -107.306      64.018
C(neighbourhood)[T.Hayes Valley]             -4.1527     48.828     -0.085      0.932     -99.861      91.556
C(neighbourhood)[T.Ingleside]               -83.5913     56.076     -1.491      0.136    -193.507      26.324
C(neighbourhood)[T.Inner Sunset]             -6.3461     45.097     -0.141      0.888     -94.742      82.050
C(neighbourhood)[T.Japantown]               -95.0846    120.703     -0.788      0.431    -331.677     141.508
C(neighbourhood)[T.Lakeshore]               -64.8910     56.215     -1.154      0.248    -175.078      45.296
C(neighbourhood)[T.Lower Haight]              5.4939     49.967      0.110      0.912     -92.447     103.435
C(neighbourhood)[T.Marina]                  110.2628     47.623      2.315      0.021      16.916     203.609
C(neighbourhood)[T.Mission Bay]               4.7683     55.676      0.086      0.932    -104.363     113.900
C(neighbourhood)[T.Mission District]          1.4577     40.234      0.036      0.971     -77.406      80.321
C(neighbourhood)[T.Mission Terrace]         -57.9228     52.489     -1.104      0.270    -160.807      44.962
C(neighbourhood)[T.Nob Hill]                 71.0870     42.047      1.691      0.091     -11.330     153.505
C(neighbourhood)[T.Noe Valley]               -5.0639     41.894     -0.121      0.904     -87.182      77.054
C(neighbourhood)[T.North Beach]              13.3754     55.720      0.240      0.810     -95.842     122.593
C(neighbourhood)[T.Oceanview]               -57.1419     58.151     -0.983      0.326    -171.124      56.840
C(neighbourhood)[T.Outer Sunset]            -71.8888     41.633     -1.727      0.084    -153.495       9.717
C(neighbourhood)[T.Pacific Heights]          67.1257     44.116      1.522      0.128     -19.346     153.597
C(neighbourhood)[T.Parkside]                114.4391     59.271      1.931      0.054      -1.739     230.617
C(neighbourhood)[T.Portola]                 -88.8387     54.183     -1.640      0.101    -195.043      17.366
C(neighbourhood)[T.Potrero Hill]              6.8201     43.711      0.156      0.876     -78.859      92.499
C(neighbourhood)[T.Presidio]                 -4.9915     94.334     -0.053      0.958    -189.897     179.914
C(neighbourhood)[T.Presidio Heights]        140.6106     65.058      2.161      0.031      13.090     268.131
C(neighbourhood)[T.Richmond District]       -34.6446     41.489     -0.835      0.404    -115.967      46.678
C(neighbourhood)[T.Russian Hill]             36.2710     47.022      0.771      0.441     -55.898     128.440
C(neighbourhood)[T.Sea Cliff]              1273.4887    208.976      6.094      0.000     863.872    1683.105
C(neighbourhood)[T.SoMa]                     79.4808     40.808      1.948      0.051      -0.507     159.469
C(neighbourhood)[T.South Beach]              24.8412     47.497      0.523      0.601     -68.258     117.941
C(neighbourhood)[T.Sunnyside]               -55.5213     48.801     -1.138      0.255    -151.176      40.134
C(neighbourhood)[T.Telegraph Hill]            8.4462     44.772      0.189      0.850     -79.312      96.204
C(neighbourhood)[T.Tenderloin]              -68.5712     47.145     -1.454      0.146    -160.980      23.838
C(neighbourhood)[T.The Castro]               25.2000     42.062      0.599      0.549     -57.246     107.646
C(neighbourhood)[T.Twin Peaks]               45.0949     52.436      0.860      0.390     -57.686     147.875
C(neighbourhood)[T.Union Square]            -63.1087     45.353     -1.391      0.164    -152.006      25.789
C(neighbourhood)[T.Visitacion Valley]       -76.7260     55.276     -1.388      0.165    -185.074      31.622
C(neighbourhood)[T.West Portal]             -55.6464    101.907     -0.546      0.585    -255.396     144.103
C(neighbourhood)[T.Western Addition/NOPA]    25.5912     40.948      0.625      0.532     -54.672     105.854
C(room_type)[T.Hotel room]                  732.5630     39.880     18.369      0.000     654.393     810.733
C(room_type)[T.Private room]                -40.7576      7.430     -5.486      0.000     -55.320     -26.195
C(room_type)[T.Shared room]                -168.5632     20.165     -8.359      0.000    -208.089    -129.037
year                                         10.7674      5.464      1.971      0.049       0.057      21.477
beds                                         73.6846      2.926     25.184      0.000      67.949      79.420
==============================================================================
Omnibus:                    32753.630   Durbin-Watson:                   1.083
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         92875128.918
Skew:                          17.156   Prob(JB):                         0.00
Kurtosis:                     373.720   Cond. No.                     6.88e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.88e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [346]:
from sklearn.metrics import r2_score

In [347]:
y_test_pred = fitted_model.predict(X_test)

In [348]:
fitted_model.params

Intercept                                   -21638.111109
C(neighbourhood)[T.Balboa Terrace]             -59.336904
C(neighbourhood)[T.Bayview]                    -74.288366
C(neighbourhood)[T.Bernal Heights]             -46.641729
C(neighbourhood)[T.Chinatown]                   18.341846
C(neighbourhood)[T.Civic Center]               246.456154
C(neighbourhood)[T.Cole Valley]                -17.123345
C(neighbourhood)[T.Cow Hollow]                  76.665000
C(neighbourhood)[T.Crocker Amazon]             -95.641535
C(neighbourhood)[T.Daly City]                 -124.821016
C(neighbourhood)[T.Diamond Heights]            -27.043493
C(neighbourhood)[T.Dogpatch]                    72.928920
C(neighbourhood)[T.Downtown]                    60.166817
C(neighbourhood)[T.Duboce Triangle]             39.722237
C(neighbourhood)[T.Excelsior]                  -97.443417
C(neighbourhood)[T.Financial District]          13.898685
C(neighbourhood)[T.Fisherman's Wharf]          225.114074
C(neighbourhood)[T.Forest Hill]                -24.908403
C(neighbourhood)[T.Glen Park]                  -27.245964
C(neighbourhood)[T.Haight-Ashbury]             -21.643993
C(neighbourhood)[T.Hayes Valley]                -4.152729
C(neighbourhood)[T.Ingleside]                  -83.591349
C(neighbourhood)[T.Inner Sunset]                -6.346061
C(neighbourhood)[T.Japantown]                  -95.084617
C(neighbourhood)[T.Lakeshore]                  -64.890958
C(neighbourhood)[T.Lower Haight]                 5.493906
C(neighbourhood)[T.Marina]                     110.262762
C(neighbourhood)[T.Mission Bay]                  4.768272
C(neighbourhood)[T.Mission District]             1.457651
C(neighbourhood)[T.Mission Terrace]            -57.922841
C(neighbourhood)[T.Nob Hill]                    71.087021
C(neighbourhood)[T.Noe Valley]                  -5.063872
C(neighbourhood)[T.North Beach]                 13.375412
C(neighbourhood)[T.Oceanview]                  -57.141909
C(neighbourhood)[T.Outer Sunset]               -71.888755
C(neighbourhood)[T.Pacific Heights]             67.125702
C(neighbourhood)[T.Parkside]                   114.439063
C(neighbourhood)[T.Portola]                    -88.838686
C(neighbourhood)[T.Potrero Hill]                 6.820138
C(neighbourhood)[T.Presidio]                    -4.991526
C(neighbourhood)[T.Presidio Heights]           140.610611
C(neighbourhood)[T.Richmond District]          -34.644587
C(neighbourhood)[T.Russian Hill]                36.270964
C(neighbourhood)[T.Sea Cliff]                 1273.488666
C(neighbourhood)[T.SoMa]                        79.480764
C(neighbourhood)[T.South Beach]                 24.841224
C(neighbourhood)[T.Sunnyside]                  -55.521275
C(neighbourhood)[T.Telegraph Hill]               8.446237
C(neighbourhood)[T.Tenderloin]                 -68.571156
C(neighbourhood)[T.The Castro]                  25.199969
C(neighbourhood)[T.Twin Peaks]                  45.094917
C(neighbourhood)[T.Union Square]               -63.108682
C(neighbourhood)[T.Visitacion Valley]          -76.725982
C(neighbourhood)[T.West Portal]                -55.646439
C(neighbourhood)[T.Western Addition/NOPA]       25.591214
C(room_type)[T.Hotel room]                     732.563041
C(room_type)[T.Private room]                   -40.757573
C(room_type)[T.Shared room]                   -168.563151
year                                            10.767371
beds                                            73.684569
dtype: float64

In [349]:
r2_score(y_test, y_test_pred)

0.13907236334986328

In [133]:
listings.head()

,Unnamed: 0,id,scrape_id,last_scraped,description,host_id,host_total_listings_count,street,neighbourhood,city,...,has_availability,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_location,review_scores_value,requires_license,license,calculated_host_listings_count,year
0,0,958,20200506054328,2020-05-06,New update: the house next door is under const...,1169,1.0,"San Francisco, CA, United States",Lower Haight,San Francisco,...,t,241,97.0,10.0,10.0,10.0,t,STR-0001256,1,2020
1,1,5858,20200506054328,2020-05-06,We live in a large Victorian house on a quiet ...,8904,2.0,"San Francisco, CA, United States",Bernal Heights,San Francisco,...,t,111,98.0,10.0,10.0,9.0,t,NaN,1,2020
2,2,7918,20200506054328,2020-05-06,Nice and good public transportation. 7 minute...,21994,10.0,"San Francisco, CA, United States",Cole Valley,San Francisco,...,t,19,84.0,7.0,9.0,8.0,t,NaN,9,2020
3,3,8142,20200506054328,2020-05-06,Nice and good public transportation. 7 minute...,21994,10.0,"San Francisco, CA, United States",Cole Valley,San Francisco,...,t,8,93.0,9.0,9.0,9.0,t,NaN,9,2020
4,4,8339,20200506054328,2020-05-06,Pls email before booking. Interior featured i...,24215,2.0,"San Francisco, CA, United States",Western Addition/NOPA,San Francisco,...,t,28,97.0,10.0,10.0,10.0,t,STR-0000264,2,2020

In [134]:
listings.groupby('neighbourhood')['price'].mean()

neighbourhood
10 min walk to Dogpatch, Mission, SOMA. Walking distance to Whole Foods, Anchor Steam Brewery, Plow, Farley's Coffee. \n\nNewly remodeled public library a 10 min walk away.\n\nPotrero Hill is known for its breathtaking downtown views, great, eclectic vibe, an    139.333333
Alamo Square                                                                                                                                                                                                                                                           281.219048
Balboa Terrace                                                                                                                                                                                                                                                         169.108333
Bayview                                                                                                                                                                                                                                                                141.994371
Bernal Heights                                                                                                                                                                                                                                                         190.310899
Chinatown                                                                                                                                                                                                                                                              209.469974
Civic Center                                                                                                                                                                                                                                                           290.408451
Cole Valley                                                                                                                                                                                                                                                            243.507353
Cow Hollow                                                                                                                                                                                                                                                             303.927711
Crocker Amazon                                                                                                                                                                                                                                                         129.818182
Daly City                                                                                                                                                                                                                                                              132.794118
Diamond Heights                                                                                                                                                                                                                                                        192.792683
Dogpatch                                                                                                                                                                                                                                                               310.834123
Downtown                                                                                                                                                                                                                                                               272.082153
Duboce Triangle                                                                                                                                                                                                                                                        230.616058
Excelsior                                                                                                                                                                                                                                                              128.884544
Fillmore District                                                                                                                                                                                                                                                      154.000000
Financial District                                                                                                                                                                                                                                                     218.221790
Fisherman's Wharf                                                                                                                                                                                                                                                      409.088319
Forest Hill                                                                                                                                                                                                                                                            207.779661
Glen Park                                                                                                                                                                                                                                                              220.170792
Haight-Ashbury                                                                                                                                                                                                                                                         218.432787
Hayes Valley                                                                                                                                                                                                                                                           239.147860
Ingleside                                                                                                                                                                                                                                                              148.833333
Inner Sunset                                                                                                                                                                                                                                                           227.866180
Japantown                                                                                                                                                                                                                                                              159.675000
Lakeshore                                                                                                                                                                                                                                                              129.433962
Lower Haight                                                                                                                                                                                                                                                           218.160976
Marina                                                                                                                                                                                                                                                                 326.137931
Mission Bay                                                                                                                                                                                                                                                            215.082474
Mission District                                                                                                                                                                                                                                                       214.716057
Mission Terrace                                                                                                                                                                                                                                                        140.314642
Nob Hill                                                                                                                                                                                                                                                               272.636063
Noe Valley                                                                                                                                                                                                                                                             238.129248
North Beach                                                                                                                                                                                                                                                            252.508721
Oceanview                                                                                                                                                                                                                                                              117.267606
Outer Sunset                                                                                                                                                                                                                                                           155.282001
Pacific Heights                                                                                                                                                                                                                                                        318.683942
Parkside                                                                                                                                                                                                                                                               206.043478
Portola                                                                                                                                                                                                                                                                150.166667
Potrero Hill                                                                                                                                                                                                                                                           244.916810
Presidio                                                                                                                                                                                                                                                               308.365854
Presidio Heights                                                                                                                                                                                                                                                       434.329480
Richmond District                                                                                                                                                                                                                                                      207.841208
Russian Hill                                                                                                                                                                                                                                                           303.055369
Sea Cliff                                                                                                                                                                                                                                                              665.571429
SoMa                                                                                                                                                                                                                                                                   274.826406
Soma                                                                                                                                                                                                                                                                   399.727273
South Beach                                                                                                                                                                                                                                                            344.564060
Sunnyside                                                                                                                                                                                                                                                              199.679912
Sunset District                                                                                                                                                                                                                                                        224.058824
Telegraph Hill                                                                                                                                                                                                                                                         253.123523
Tenderloin                                                                                                                                                                                                                                                             127.052525
The Castro                                                                                                                                                                                                                                                             244.779420
Twin Peaks                                                                                                                                                                                                                                                             242.863636
Union Square                                                                                                                                                                                                                                                           153.021544
Visitacion Valley                                                                                                                                                                                                                                                      148.843575
West Portal                                                                                                                                                                                                                                                            123.017544
Western Addition                                                                                                                                                                                                                                                       214.600000
Western Addition/NOPA                                                                                                                                                                                                                                                  251.194456
Name: price, dtype: float64

In [136]:
listings.pivot_table(index = 'neighbourhood', values= ['price', 'has_availability'], aggfunc=sum)

                                                        price
neighbourhood
10 min walk to Dogpatch, Mission, SOMA. Walking...      418.0
Alamo Square                                         118112.0
Balboa Terrace                                        40586.0
Bayview                                              151366.0
Bernal Heights                                       378909.0
Chinatown                                             80227.0
Civic Center                                          41238.0
Cole Valley                                          132468.0
Cow Hollow                                           126130.0
Crocker Amazon                                        35700.0
Daly City                                             13545.0
Diamond Heights                                       15809.0
Dogpatch                                              65586.0
Downtown                                             288135.0
Duboce Triangle                                      157972.0
Excelsior                                             69211.0
Fillmore District                                       770.0
Financial District                                   112166.0
Fisherman's Wharf                                    143590.0
Forest Hill                                           12259.0
Glen Park                                             88949.0
Haight-Ashbury                                       199866.0
Hayes Valley                                         122922.0
Ingleside                                             30362.0
Inner Sunset                                         187306.0
Japantown                                              6387.0
Lakeshore                                             27440.0
Lower Haight                                         134169.0
Marina                                               236450.0
Mission Bay                                           41726.0
Mission District                                    1004227.0
Mission Terrace                                       45041.0
Nob Hill                                             412771.0
Noe Valley                                           392437.0
North Beach                                           86863.0
Oceanview                                             24978.0
Outer Sunset                                         238979.0
Pacific Heights                                      375091.0
Parkside                                              66346.0
Portola                                               30634.0
Potrero Hill                                         285573.0
Presidio                                              37929.0
Presidio Heights                                      75139.0
Richmond District                                    426698.0
Russian Hill                                         180621.0
Sea Cliff                                              9318.0
SoMa                                                 786828.0
Soma                                                   4397.0
South Beach                                          207083.0
Sunnyside                                             90455.0
Sunset District                                        3809.0
Telegraph Hill                                       235658.0
Tenderloin                                            62891.0
The Castro                                           413922.0
Twin Peaks                                            96174.0
Union Square                                          85233.0
Visitacion Valley                                     26643.0
West Portal                                            7012.0
Western Addition                                       2146.0
Western Addition/NOPA                                607137.0

In [138]:
listings.groupby('neighbourhood')['has_availability'].value_counts()

neighbourhood          has_availability
Alamo Square           t                    114
Balboa Terrace         t                    111
Bayview                t                    801
Bernal Heights         t                    988
Chinatown              t                    151
Civic Center           t                     58
Cole Valley            t                    250
Cow Hollow             t                    166
Crocker Amazon         t                    168
Daly City              t                     68
Diamond Heights        t                     35
Dogpatch               t                    101
Downtown               t                    727
Duboce Triangle        t                    322
Excelsior              t                    320
Financial District     t                    396
Fisherman's Wharf      t                    232
Forest Hill            t                     29
Glen Park              t                    184
Haight-Ashbury         t                    430
Hayes Valley           t                    204
Ingleside              t                    105
Inner Sunset           t                    467
Japantown              t                     13
Lakeshore              t                    104
Lower Haight           t                    175
Marina                 t                    294
Mission Bay            t                    151
Mission District       t                   1981
Mission Terrace        t                    155
Nob Hill               t                    713
Noe Valley             t                    727
North Beach            t                    131
Oceanview              t                     92
Outer Sunset           t                    917
Pacific Heights        t                    480
Parkside               t                     87
Portola                t                    133
Potrero Hill           t                    502
Presidio               t                    111
Presidio Heights       t                     69
Richmond District      t                    933
Russian Hill           t                    282
Sea Cliff              t                      4
SoMa                   t                   1540
South Beach            t                    303
Sunnyside              t                    223
Telegraph Hill         t                    613
Tenderloin             t                    241
The Castro             t                    779
Twin Peaks             t                    183
Union Square           t                    317
Visitacion Valley      t                    118
West Portal            t                     19
Western Addition/NOPA  t                   1387
Name: has_availability, dtype: int64

In [139]:
listings.groupby('neighbourhood')['id'].sum()

neighbourhood
10 min walk to Dogpatch, Mission, SOMA. Walking distance to Whole Foods, Anchor Steam Brewery, Plow, Farley's Coffee. \n\nNewly remodeled public library a 10 min walk away.\n\nPotrero Hill is known for its breathtaking downtown views, great, eclectic vibe, an        3067080
Alamo Square                                                                                                                                                                                                                                                            4240081959
Balboa Terrace                                                                                                                                                                                                                                                          2693303801
Bayview                                                                                                                                                                                                                                                                16122312515
Bernal Heights                                                                                                                                                                                                                                                         19905497723
Chinatown                                                                                                                                                                                                                                                               5151288292
Civic Center                                                                                                                                                                                                                                                            1986914585
Cole Valley                                                                                                                                                                                                                                                             6050006005
Cow Hollow                                                                                                                                                                                                                                                              4392548947
Crocker Amazon                                                                                                                                                                                                                                                          4721313071
Daly City                                                                                                                                                                                                                                                               1743828567
Diamond Heights                                                                                                                                                                                                                                                          793110779
Dogpatch                                                                                                                                                                                                                                                                2618161848
Downtown                                                                                                                                                                                                                                                               21039096008
Duboce Triangle                                                                                                                                                                                                                                                         8096584037
Excelsior                                                                                                                                                                                                                                                               6737544588
Fillmore District                                                                                                                                                                                                                                                          2237827
Financial District                                                                                                                                                                                                                                                      7869531856
Fisherman's Wharf                                                                                                                                                                                                                                                       5385368243
Forest Hill                                                                                                                                                                                                                                                              704283017
Glen Park                                                                                                                                                                                                                                                               3748292765
Haight-Ashbury                                                                                                                                                                                                                                                         10708244349
Hayes Valley                                                                                                                                                                                                                                                            6706159542
Ingleside                                                                                                                                                                                                                                                               2837787403
Inner Sunset                                                                                                                                                                                                                                                           10622558439
Japantown                                                                                                                                                                                                                                                                617825329
Lakeshore                                                                                                                                                                                                                                                               3200893770
Lower Haight                                                                                                                                                                                                                                                            5546090517
Marina                                                                                                                                                                                                                                                                  6559902099
Mission Bay                                                                                                                                                                                                                                                             3904332453
Mission District                                                                                                                                                                                                                                                       46066758867
Mission Terrace                                                                                                                                                                                                                                                         3834331557
Nob Hill                                                                                                                                                                                                                                                               22536605922
Noe Valley                                                                                                                                                                                                                                                             17260758011
North Beach                                                                                                                                                                                                                                                             4016852132
Oceanview                                                                                                                                                                                                                                                               3510116850
Outer Sunset                                                                                                                                                                                                                                                           21972024053
Pacific Heights                                                                                                                                                                                                                                                        11796229702
Parkside                                                                                                                                                                                                                                                                3650347208
Portola                                                                                                                                                                                                                                                                 3873952315
Potrero Hill                                                                                                                                                                                                                                                           11704636063
Presidio                                                                                                                                                                                                                                                                1433464944
Presidio Heights                                                                                                                                                                                                                                                        1679079435
Richmond District                                                                                                                                                                                                                                                      24875727979
Russian Hill                                                                                                                                                                                                                                                            7229729539
Sea Cliff                                                                                                                                                                                                                                                                170400304
SoMa                                                                                                                                                                                                                                                                   42216177823
Soma                                                                                                                                                                                                                                                                       4265855
South Beach                                                                                                                                                                                                                                                             8842322094
Sunnyside                                                                                                                                                                                                                                                               5167678493
Sunset District                                                                                                                                                                                                                                                            6823620
Telegraph Hill                                                                                                                                                                                                                                                         10940862942
Tenderloin                                                                                                                                                                                                                                                              8200639248
The Castro                                                                                                                                                                                                                                                             17297278454
Twin Peaks                                                                                                                                                                                                                                                              4228260733
Union Square                                                                                                                                                                                                                                                            9099947100
Visitacion Valley                                                                                                                                                                                                                                                       3100430906
West Portal                                                                                                                                                                                                                                                              521871529
Western Addition                                                                                                                                                                                                                                                           3797682
Western Addition/NOPA                                                                                                                                                                                                                                                  28442831843
Name: id, dtype: int64

In [141]:
listings.pivot_table(index = 'neighbourhood', values= ['price', 'id'], aggfunc=

SyntaxError: unexpected EOF while parsing (<ipython-input-141-9e0005a4ef0e>, line 1)